include:
  remote: https://git.sr.solutions/gitlab-ci/templates/review.yml

stages:
  - review

review:
  extends: .review_deployment
  variables:
    REVIEW_APP_IMAGE: srsolutions/ilias:8-php7.4-apache
    REVIEW_APP_DEST: /var/www/html/Customizing/global/plugins/Services/COPage/PageComponent/SrExternalPageContent
    ILIAS_DEVMODE: 1
    ILIAS_INSTALL_ARGUMENTS: --no-plugins
    REVIEW_APP_STACK_CONFIG: /etc/docker/stacks/ilias-plugin.yml
  extends: .review_deployment
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    url: http://${CI_PROJECT_PATH_SLUG}_${CI_COMMIT_REF_SLUG}.review.sr.solutions
    on_stop: stop_review
  script:
    - srag-review deploy

stop_review:
  extends: .review_deployment
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    action: stop
  script:
    - srag-review stop
