stages:
  - build
  - review
  - sync

include:
  - component: $CI_SERVER_FQDN/Intern/gitlab-ci-components/build-ilias@master
    inputs:
      ilias_image: "srsolutions/ilias:8"
      target_dir: Customizing/global/plugins/Services/COPage/PageComponent/SrExternalPageContent
    rules:
      - if: $CI_COMMIT_BRANCH

  - component: $CI_SERVER_FQDN/Intern/gitlab-ci-components/review-ilias@master
    inputs:
      app_name: srexternalpagecontent-${CI_COMMIT_REF_SLUG}
    rules:
      - if: $CI_COMMIT_BRANCH

  - component: $CI_SERVER_FQDN/Intern/gitlab-ci-components/sync-ilias@master
    inputs:
      src_namespace: ilias-plugins-internal-srexternalpagecontent-release_8
      dest_namespace: srexternalpagecontent-${CI_COMMIT_REF_SLUG}
    rules:
      - if: $CI_COMMIT_BRANCH != "release_8"