stages:
  - build
  - review
  - sync

include:
  - component: $CI_SERVER_FQDN/Intern/gitlab-ci-components/build-ilias@master
    inputs:
      ilias_image: "srsolutions/ilias:8"
      target_dir: Customizing/global/plugins/Services/COPage/PageComponent/SrExternalPageContent

  - component: $CI_SERVER_FQDN/Intern/gitlab-ci-components/review-ilias@master

  - component: $CI_SERVER_FQDN/Intern/gitlab-ci-components/sync-ilias@master
    inputs:
      src_namespace: ilias-plugins-internal-srexternalpagecontent-release_8
    rules:
      - if: $CI_COMMIT_BRANCH != "release_8"

build:
  # Override trigger
  when: manual